# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(max_length=200)),
                ('street_2', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('zipcode', models.IntegerField(db_index=True)),
                ('latitude', models.FloatField(blank=True, db_index=True)),
                ('longitude', models.FloatField(blank=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='STVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addresses', models.ManyToManyField(to='campfin_data.Address')),
            ],
        ),
        migrations.CreateModel(
            name='STVendorContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bid', models.DecimalField(blank=True, decimal_places=3, max_digits=15)),
                ('amount_awarded', models.DecimalField(blank=True, decimal_places=3, max_digits=15)),
                ('contract_name', models.TextField(db_index=True)),
                ('solicitation_id', models.CharField(db_index=True, max_length=20)),
                ('award_date', models.DateTimeField(blank=True, db_index=True)),
                ('not_lowest', models.BooleanField(default=False)),
                ('only_bidder', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('st2_related', models.BooleanField(default=False)),
                ('st3_related', models.BooleanField(default=False)),
                ('all_one_dollar_bids', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.STVendor')),
            ],
        ),
    ]
