# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
