# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0003_auto_20160421_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
