# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0004_auto_20160421_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode_plus',
            field=models.IntegerField(null=True),
        ),
    ]
