# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0009_auto_20160421_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='address',
            name='original_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode_plus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stvendorcontract',
            name='amount_awarded',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stvendorcontract',
            name='amount_bid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stvendorcontract',
            name='award_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
