# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0010_auto_20160421_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSCorporatePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SOSCorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubi', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('state_incorporation', models.CharField(db_index=True, max_length=2)),
                ('category', models.CharField(db_index=True, max_length=10)),
                ('date_incorporation', models.DateField(blank=True, db_index=True, null=True)),
                ('date_expiration', models.DateField(blank=True, db_index=True, null=True)),
                ('date_dissolution', models.DateField(blank=True, db_index=True, null=True)),
                ('record_status', models.CharField(db_index=True, max_length=10)),
                ('corp_type', models.CharField(db_index=True, max_length=10)),
                ('alternate_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SOSGoverningPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.SOSCorporation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.SOSCorporatePerson')),
            ],
        ),
        migrations.AddField(
            model_name='soscorporation',
            name='governing_persons',
            field=models.ManyToManyField(related_name='governing_persons', through='campfin_data.SOSGoverningPerson', to='campfin_data.SOSCorporatePerson'),
        ),
        migrations.AddField(
            model_name='soscorporation',
            name='registered_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_agent', to='campfin_data.SOSCorporatePerson'),
        ),
    ]
