# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0011_auto_20160422_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soscorporation',
            name='registered_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_agent', to='campfin_data.SOSCorporatePerson'),
        ),
    ]
