# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0013_auto_20160422_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soscorporateperson',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Address'),
        ),
    ]
