# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0014_auto_20160422_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soscorporation',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
