# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0015_auto_20160422_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soscorporateperson',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='soscorporateperson',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='soscorporateperson',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
