# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0016_auto_20160422_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('repno', models.IntegerField(db_index=True)),
                ('filer_id', models.CharField(db_index=True, max_length=30)),
                ('rec_type', models.CharField(db_index=True, max_length=10)),
                ('form_type', models.CharField(db_index=True, max_length=10)),
                ('rpt_date', models.DateField(db_index=True)),
                ('prim_gen', models.CharField(db_index=True, max_length=3)),
                ('rcpt_date', models.DateField(db_index=True)),
                ('donor_employer', models.CharField(db_index=True, max_length=150, null=True)),
                ('donor_occupation', models.CharField(db_index=True, max_length=150, null=True)),
                ('donor_employer_city', models.CharField(db_index=True, max_length=100, null=True)),
                ('donor_employer_state', models.CharField(max_length=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('aggregate', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('memo', models.TextField(null=True)),
                ('code', models.CharField(db_index=True, max_length=50, null=True)),
                ('contribution_type', models.CharField(db_index=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SOSCorporatePerson',
            new_name='Person',
        ),
        migrations.AddField(
            model_name='pdccontribution',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Person'),
        ),
        migrations.AddField(
            model_name='pdccontribution',
            name='donor_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Address'),
        ),
    ]
