# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0020_auto_20160426_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
