# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0022_address_geocode_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soscorporation',
            name='category',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='soscorporation',
            name='corp_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='soscorporation',
            name='record_status',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
