# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0024_auto_20160501_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_1',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
