# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0026_auto_20160505_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geocode_confidence',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
