# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0027_auto_20160505_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geocode_provider',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
    ]
