# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0028_address_geocode_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='census_block',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='census_county_fips',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='census_tract',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='census_year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
