# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0032_auto_20160518_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdclobbyistemployeryear',
            name='pacs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
