# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0033_auto_20160518_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCLobbyingFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.PDCLobbyistEmployer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='campfin_data.PDCLobbyist')),
                ('lobbyist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbyist', to='campfin_data.PDCLobbyist')),
            ],
        ),
    ]
