# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0034_pdclobbyingfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCLobbyistBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('year_first_employed', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('lobbyist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.PDCLobbyist')),
            ],
        ),
    ]
