# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0035_pdclobbyistbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdclobbyistbio',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
