# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0037_pdclobbyistmonthlyexpensereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdclobbyistmonthlyexpensereport',
            name='total_expenses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
