# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0038_pdclobbyistmonthlyexpensereport_total_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(db_index=True, max_length=30)),
                ('link_source', models.CharField(db_index=True, max_length=30)),
                ('links', models.ManyToManyField(db_index=True, to='campfin_data.Person')),
            ],
        ),
    ]
