# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0039_personlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repno', models.IntegerField(db_index=True)),
                ('filer_id', models.CharField(db_index=True, max_length=30)),
                ('is_superseded', models.BooleanField(db_index=True, default=False)),
                ('superseding_report_no', models.IntegerField(blank=True, db_index=True, null=True)),
                ('election_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('filer_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('date_filed', models.DateField(blank=True, db_index=True, null=True)),
                ('form', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('subform', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('period_from', models.DateField(blank=True, db_index=True, null=True)),
                ('period_thru', models.DateField(blank=True, db_index=True, null=True)),
                ('doe', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('how_filed', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('received', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('rptcode', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('filer_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.PDCCommittee')),
                ('superseding_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superseded_report', to='campfin_data.PDCReport')),
            ],
        ),
        migrations.AddField(
            model_name='pdccontribution',
            name='is_superseded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
