# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0040_auto_20160524_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personlink',
            name='links',
        ),
        migrations.AddField(
            model_name='personlink',
            name='canonical',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='canonical', to='campfin_data.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personlink',
            name='secondary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='campfin_data.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personlink',
            name='link_type',
            field=models.CharField(choices=[('SM', 'Same'), ('PT', 'Partner')], db_index=True, default='SM', max_length=2),
        ),
    ]
