# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0041_auto_20160525_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='STVendorBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.CharField(db_index=True, max_length=15)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Person')),
            ],
        ),
        migrations.CreateModel(
            name='STVendorContractBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=15)),
                ('po_type', models.CharField(db_index=True, max_length=15)),
                ('procurement_number', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('po_description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('close_date', models.DateField(blank=True, db_index=True, null=True)),
                ('award', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('expenditures', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('award_remaining', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('unreleased', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('contract_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_specialist', to='campfin_data.Person')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='campfin_data.Person')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.STVendorBrief')),
            ],
        ),
    ]
