# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0042_stvendorbrief_stvendorcontractbrief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stvendorcontractbrief',
            name='procurement_number',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True),
        ),
    ]
