# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0043_auto_20160525_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stvendorbrief',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.Person'),
        ),
    ]
