# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0045_auto_20160526_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdccommitteeyear',
            name='ballot_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdccommitteeyear',
            name='ballot_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pdccommitteeyear',
            name='for_against',
            field=models.CharField(blank=True, choices=[('F', 'For'), ('A', 'Against')], db_index=True, default='F', max_length=1, null=True),
        ),
    ]
