# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0047_soselectioncandidate_soselectionrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soselectionrace',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidate', to='campfin_data.SOSElectionCandidate'),
        ),
        migrations.AlterField(
            model_name='soselectionrace',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='campfin_data.SOSElectionCandidate'),
        ),
    ]
