# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0048_auto_20160531_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soselectionrace',
            name='candidates',
            field=models.ManyToManyField(related_name='candidate', to='campfin_data.SOSElectionCandidate'),
        ),
    ]
