# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0049_auto_20160531_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soselectionrace',
            name='jurisdiction',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
