# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0053_geography_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='shapefile',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
