# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0055_auto_20160714_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPrecinctCrosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=10)),
                ('district_type', models.CharField(db_index=True, max_length=50)),
                ('district_id', models.IntegerField(db_index=True)),
                ('district_code', models.CharField(db_index=True, max_length=15)),
                ('district_name', models.CharField(db_index=True, max_length=250)),
                ('precinct_code', models.IntegerField(db_index=True)),
                ('precinct_part', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='VTDPrecinctCrosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=10)),
                ('precinct_code', models.CharField(db_index=True, max_length=50)),
                ('precinct_part', models.CharField(db_index=True, max_length=15)),
                ('vtd_identifier', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
