# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0056_districtprecinctcrosswalk_vtdprecinctcrosswalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(db_index=True, max_length=50)),
                ('race_position_name', models.CharField(db_index=True, max_length=50)),
                ('candidate_name', models.CharField(db_index=True, max_length=200)),
                ('party_name', models.CharField(db_index=True, max_length=50)),
                ('county_display', models.CharField(db_index=True, max_length=250)),
            ],
        ),
    ]
