# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0057_racecandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_name', models.CharField(db_index=True, max_length=200)),
                ('candidate_id', models.IntegerField(db_index=True)),
                ('city', models.CharField(db_index=True, max_length=200)),
                ('display_order_general', models.IntegerField()),
                ('display_order_primary', models.IntegerField()),
                ('election_year', models.IntegerField()),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('is_filing_approved', models.BooleanField(db_index=True)),
                ('is_locked_out_general', models.BooleanField(db_index=True)),
                ('is_locked_out_primary', models.BooleanField(db_index=True)),
                ('is_withdrawn', models.BooleanField(db_index=True)),
                ('is_writein', models.BooleanField(db_index=True)),
                ('party_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BallotDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=2)),
                ('display_order', models.IntegerField()),
                ('district_code', models.CharField(db_index=True, max_length=10)),
                ('district_id', models.IntegerField(db_index=True)),
                ('district_name', models.CharField(db_index=True, max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_state_category', models.BooleanField(db_index=True)),
                ('is_usable_by_measure', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BallotDistrictDistrictMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='campfin_data.BallotDistrict')),
                ('parent_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='campfin_data.BallotDistrict')),
            ],
        ),
        migrations.CreateModel(
            name='BallotDistrictPrecinctMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=2)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotDistrict')),
            ],
        ),
        migrations.CreateModel(
            name='BallotDistrictType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('district_type', models.CharField(max_length=100)),
                ('district_type_code', models.CharField(max_length=10)),
                ('district_type_id', models.IntegerField(db_index=True)),
                ('type_description', models.CharField(max_length=100)),
                ('is_federal_category', models.BooleanField(db_index=True)),
                ('is_state_category', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BallotElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateField(db_index=True)),
                ('election_date', models.DateField(db_index=True)),
                ('election_name', models.CharField(db_index=True, max_length=50)),
                ('election_id', models.IntegerField(db_index=True)),
                ('general_election_id', models.IntegerField(db_index=True)),
                ('is_current', models.BooleanField(db_index=True)),
                ('is_general', models.BooleanField(db_index=True)),
                ('is_special', models.BooleanField(db_index=True)),
                ('is_state_primary', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BallotOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('election_code', models.CharField(db_index=True, max_length=25)),
                ('office_id', models.IntegerField(db_index=True)),
                ('office_name', models.CharField(max_length=100)),
                ('reporting_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotDistrict')),
                ('general_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_election', to='campfin_data.BallotElection')),
                ('primary_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_election', to='campfin_data.BallotElection')),
                ('subject_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_election', to='campfin_data.BallotElection')),
            ],
        ),
        migrations.CreateModel(
            name='BallotPrecinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=2)),
                ('levy_code', models.IntegerField(db_index=True)),
                ('precinct_code', models.IntegerField(db_index=True)),
                ('precinct_id', models.IntegerField(db_index=True)),
                ('precinct_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BallotRaceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_display_order', models.IntegerField()),
                ('ballot_id', models.IntegerField(db_index=True)),
                ('ballot_name', models.CharField(max_length=100)),
                ('ballot_name_with_party', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=2)),
                ('county_display', models.CharField(max_length=100)),
                ('county_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField()),
                ('party_code', models.CharField(max_length=10)),
                ('party_name', models.CharField(max_length=50)),
                ('race_id', models.IntegerField(db_index=True)),
                ('race_name', models.CharField(max_length=300)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotDistrict')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotElection')),
            ],
        ),
        migrations.AddField(
            model_name='ballotdistrictprecinctmap',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotPrecinct'),
        ),
        migrations.AddField(
            model_name='ballotdistrict',
            name='district_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotDistrictType'),
        ),
        migrations.AddField(
            model_name='ballotcandidate',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotOffice'),
        ),
    ]
