# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0059_auto_20160801_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotelection',
            name='certification_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballotelection',
            name='election_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
