# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0060_auto_20160801_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotdistrict',
            name='district_code',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
