# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0061_auto_20160801_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotdistrict',
            name='district_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotDistrictType'),
        ),
        migrations.AlterField(
            model_name='ballotoffice',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
