# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0064_auto_20160802_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotcandidate',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.BallotOffice'),
        ),
    ]
