# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0066_auto_20160802_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotcandidate',
            name='display_order_general',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballotcandidate',
            name='display_order_primary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
