# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0067_auto_20160802_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotracesummary',
            name='ballot_display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballotracesummary',
            name='ballot_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballotracesummary',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
