# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0070_auto_20160802_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotracesummary',
            name='ballot_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ballotracesummary',
            name='county_display',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ballotracesummary',
            name='race_name',
            field=models.CharField(max_length=500),
        ),
    ]
