# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0071_auto_20160802_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotracesummary',
            name='ballot_name_with_party',
            field=models.CharField(max_length=750),
        ),
    ]
