# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0073_sospdcmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCommittee',
            fields=[
                ('filer_id', models.CharField(db_index=True, max_length=30, serialize=False)),
                ('pdc_url', models.URLField()),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('party', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=250)),
                ('committee_group', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(db_index=True, max_length=500)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('primary_general', models.CharField(db_index=True, max_length=15)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('zipcode', models.CharField(db_index=True, max_length=11)),
                ('employer', models.CharField(db_index=True, max_length=100)),
                ('occupation', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(db_index=True, max_length=300)),
            ],
        ),
    ]
