# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0074_scrapedcommittee_scrapedcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontribution',
            name='filing_committee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='campfin_data.ScrapedCommittee'),
            preserve_default=False,
        ),
    ]
