# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0076_auto_20160809_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcommittee',
            name='committee_group',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
