# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0078_auto_20160810_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcontribution',
            name='primary_general',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
