# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0079_auto_20160816_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcontribution',
            name='zipcode',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
    ]
