# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0081_auto_20160816_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcontribution',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedcontribution',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
