# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0083_auto_20160816_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedexpense',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedexpense',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedexpense',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedexpense',
            name='zipcode',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
    ]
