# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0085_scrapedtotals'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='geo_type',
            field=models.CharField(default='oneoff', max_length=100),
        ),
    ]
