# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0086_geography_geo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(db_index=True, max_length=500)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('filing_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campfin_data.ScrapedCommittee')),
            ],
        ),
    ]
