# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0087_scrapedrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedupedCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scrapedcontribution',
            name='dedupe_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campfin_data.DedupedCluster'),
        ),
    ]
