# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campfin_data', '0090_auto_20161213_1709'),
    ]

    operations = [
    ]
